using OpenQA.Selenium;
using ExpectedConditions = SeleniumExtras.WaitHelpers.ExpectedConditions;
using Core.Base;
using Core.Driver;
using OpenQA.Selenium.Support.UI;
using System.Collections.ObjectModel;
using System.Reflection;

namespace OR_Follow_Ups
{
    public partial class Follow_Ups
    {
        public IWebElement AddContactLink => Browser.FindElement(By.Id("AddContactLink"));
        public IWebElement AddFollowupLink => Browser.FindElement(By.Id("AddFollowupLink"));
        public IWebElement AddNewFollowupModalLink => Browser.FindElement(By.Id("AddNewFollowupModalLink"));
        public IWebElement AddOrganizationLink => Browser.FindElement(By.Id("AddOrganizationLink"));
        public IWebElement AnchorOpenCalendar_FromDateField => Browser.FindElement(By.Id("AnchorOpenCalendar_FromDateField"));
        public IWebElement AnchorOpenCalendar_ToDateField => Browser.FindElement(By.Id("AnchorOpenCalendar_ToDateField"));
        public IWebElement AppLogoLink => Browser.FindElement(By.Id("AppLogoLink"));
        public IWebElement CalendarViewButton => Browser.FindElement(By.Id("CalendarViewButton"));
        public IWebElement ClearButton => Browser.FindElement(By.Id("ClearButton"));
        public IWebElement CompleteSelectField => Browser.FindElement(By.Id("CompleteSelectField"));
        public SelectElement CompleteSelectFieldOption => new SelectElement(CompleteSelectField);
        public ReadOnlyCollection<IWebElement> CompleteSelectFieldOptionsUl => Browser.FindElements(By.XPath("//*[@id='CompleteSelectFieldOptionsUl']//li//a"));
        public IWebElement CompleteSelectFieldSelectedAnchor => Browser.FindElement(By.Id("CompleteSelectFieldSelectedAnchor"));
        public IWebElement ContactField => Browser.FindElement(By.Id("ContactField"));
        public IWebElement ContactSummaryLinkGTC43az2tfR9mR1al472h8AP6Ig6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTC43az2tfR9mR1al472h8AP6Ig6161"));
        public IWebElement ContactSummaryLinkGTC47jpGaAfgHdno43wvWmvV43xQ6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTC47jpGaAfgHdno43wvWmvV43xQ6161"));
        public IWebElement ContactSummaryLinkGTC6C1CRHkDt6b0KVXHCdPjbg6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTC6C1CRHkDt6b0KVXHCdPjbg6161"));
        public IWebElement ContactSummaryLinkGTC7teUUHinAF2avtmvukp5Ag6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTC7teUUHinAF2avtmvukp5Ag6161"));
        public IWebElement ContactSummaryLinkGTCAxTWsbQ3GJcXjtrxdbcpJA6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCAxTWsbQ3GJcXjtrxdbcpJA6161"));
        public IWebElement ContactSummaryLinkGTCCV3Yzj7qYqEK1zIGQGMgSg6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCCV3Yzj7qYqEK1zIGQGMgSg6161"));
        public IWebElement ContactSummaryLinkGTCEGhSjJkjS47J8WIvkZLFGPQ6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCEGhSjJkjS47J8WIvkZLFGPQ6161"));
        public IWebElement ContactSummaryLinkGTCJ9YXdwOW2uDrZJoL84ZqGg6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCJ9YXdwOW2uDrZJoL84ZqGg6161"));
        public IWebElement ContactSummaryLinkGTCJEKHflaoib8QnrpzOP9qWQ6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCJEKHflaoib8QnrpzOP9qWQ6161"));
        public IWebElement ContactSummaryLinkGTCLLcuT471gV143mygHnPkKt0A6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCLLcuT471gV143mygHnPkKt0A6161"));
        public IWebElement ContactSummaryLinkGTCM7fr7wz43nRP7pxgAEXP4BQ6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCM7fr7wz43nRP7pxgAEXP4BQ6161"));
        public IWebElement ContactSummaryLinkGTCXxkTFvpyDa47UwrjBNBbYPw6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCXxkTFvpyDa47UwrjBNBbYPw6161"));
        public IWebElement ContactSummaryLinkGTCYJVZ74ieyWJIx434398WxOjg6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCYJVZ74ieyWJIx434398WxOjg6161"));
        public IWebElement ContactSummaryLinkGTCqC9lKip9hliHH43431qc2nPQ6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCqC9lKip9hliHH43431qc2nPQ6161"));
        public IWebElement ContactSummaryLinkGTCqr47WhlV1UmigenKGmCfcdQ6161 => Browser.FindElement(By.Id("ContactSummaryLinkGTCqr47WhlV1UmigenKGmCfcdQ6161"));
        public IWebElement ContactsButton => Browser.FindElement(By.Id("ContactsButton"));
        public IWebElement ContactsReportLink => Browser.FindElement(By.Id("ContactsReportLink"));
        public IWebElement FollowupPanel => Browser.FindElement(By.Id("FollowupPanel"));
        public IWebElement FollowupSummaryLinkGTC43az2tfR9mR1al472h8AP6Ig6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTC43az2tfR9mR1al472h8AP6Ig6161"));
        public IWebElement FollowupSummaryLinkGTC47jpGaAfgHdno43wvWmvV43xQ6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTC47jpGaAfgHdno43wvWmvV43xQ6161"));
        public IWebElement FollowupSummaryLinkGTC6C1CRHkDt6b0KVXHCdPjbg6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTC6C1CRHkDt6b0KVXHCdPjbg6161"));
        public IWebElement FollowupSummaryLinkGTC7teUUHinAF2avtmvukp5Ag6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTC7teUUHinAF2avtmvukp5Ag6161"));
        public IWebElement FollowupSummaryLinkGTCAxTWsbQ3GJcXjtrxdbcpJA6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCAxTWsbQ3GJcXjtrxdbcpJA6161"));
        public IWebElement FollowupSummaryLinkGTCCV3Yzj7qYqEK1zIGQGMgSg6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCCV3Yzj7qYqEK1zIGQGMgSg6161"));
        public IWebElement FollowupSummaryLinkGTCEGhSjJkjS47J8WIvkZLFGPQ6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCEGhSjJkjS47J8WIvkZLFGPQ6161"));
        public IWebElement FollowupSummaryLinkGTCJ9YXdwOW2uDrZJoL84ZqGg6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCJ9YXdwOW2uDrZJoL84ZqGg6161"));
        public IWebElement FollowupSummaryLinkGTCJEKHflaoib8QnrpzOP9qWQ6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCJEKHflaoib8QnrpzOP9qWQ6161"));
        public IWebElement FollowupSummaryLinkGTCLLcuT471gV143mygHnPkKt0A6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCLLcuT471gV143mygHnPkKt0A6161"));
        public IWebElement FollowupSummaryLinkGTCM7fr7wz43nRP7pxgAEXP4BQ6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCM7fr7wz43nRP7pxgAEXP4BQ6161"));
        public IWebElement FollowupSummaryLinkGTCXxkTFvpyDa47UwrjBNBbYPw6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCXxkTFvpyDa47UwrjBNBbYPw6161"));
        public IWebElement FollowupSummaryLinkGTCYJVZ74ieyWJIx434398WxOjg6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCYJVZ74ieyWJIx434398WxOjg6161"));
        public IWebElement FollowupSummaryLinkGTCqC9lKip9hliHH43431qc2nPQ6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCqC9lKip9hliHH43431qc2nPQ6161"));
        public IWebElement FollowupSummaryLinkGTCqr47WhlV1UmigenKGmCfcdQ6161 => Browser.FindElement(By.Id("FollowupSummaryLinkGTCqr47WhlV1UmigenKGmCfcdQ6161"));
        public IWebElement FollowupTypeField => Browser.FindElement(By.Id("FollowupTypeField"));
        public SelectElement FollowupTypeFieldOption => new SelectElement(FollowupTypeField);
        public ReadOnlyCollection<IWebElement> FollowupTypeFieldOptionsUl => Browser.FindElements(By.XPath("//*[@id='FollowupTypeFieldOptionsUl']//li//a"));
        public IWebElement FollowupTypeFieldSelectedAnchor => Browser.FindElement(By.Id("FollowupTypeFieldSelectedAnchor"));
        public IWebElement FollowupsButton => Browser.FindElement(By.Id("FollowupsButton"));
        public IWebElement FollowupsReportLink => Browser.FindElement(By.Id("FollowupsReportLink"));
        public IWebElement FromDateField => Browser.FindElement(By.Id("FromDateField"));
        public IWebElement GTC210b4d8a_671c_40f5_805d_daffe47b42f8 => Browser.FindElement(By.Id("GTC210b4d8a_671c_40f5_805d_daffe47b42f8"));
        public IWebElement GTCe26539f6_0ccb_4e88_9cf5_5390cb56677d => Browser.FindElement(By.Id("GTCe26539f6_0ccb_4e88_9cf5_5390cb56677d"));
        public IWebElement GridViewButton => Browser.FindElement(By.Id("GridViewButton"));
        public IWebElement LPOOwnerField => Browser.FindElement(By.Id("LPOOwnerField"));
        public SelectElement LPOOwnerFieldOption => new SelectElement(LPOOwnerField);
        public ReadOnlyCollection<IWebElement> LPOOwnerFieldOptionsUl => Browser.FindElements(By.XPath("//*[@id='LPOOwnerFieldOptionsUl']//li//a"));
        public IWebElement LPOOwnerFieldSelectedAnchor => Browser.FindElement(By.Id("LPOOwnerFieldSelectedAnchor"));
        public IWebElement LogoffLinkName => Browser.FindElement(By.Id("LogoffLinkName"));
        public IWebElement OrganizationField => Browser.FindElement(By.Id("OrganizationField"));
        public IWebElement OrganizationSummaryLinkGTC43az2tfR9mR1al472h8AP6Ig6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTC43az2tfR9mR1al472h8AP6Ig6161"));
        public IWebElement OrganizationSummaryLinkGTC47jpGaAfgHdno43wvWmvV43xQ6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTC47jpGaAfgHdno43wvWmvV43xQ6161"));
        public IWebElement OrganizationSummaryLinkGTC6C1CRHkDt6b0KVXHCdPjbg6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTC6C1CRHkDt6b0KVXHCdPjbg6161"));
        public IWebElement OrganizationSummaryLinkGTC7teUUHinAF2avtmvukp5Ag6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTC7teUUHinAF2avtmvukp5Ag6161"));
        public IWebElement OrganizationSummaryLinkGTCAxTWsbQ3GJcXjtrxdbcpJA6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCAxTWsbQ3GJcXjtrxdbcpJA6161"));
        public IWebElement OrganizationSummaryLinkGTCCV3Yzj7qYqEK1zIGQGMgSg6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCCV3Yzj7qYqEK1zIGQGMgSg6161"));
        public IWebElement OrganizationSummaryLinkGTCEGhSjJkjS47J8WIvkZLFGPQ6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCEGhSjJkjS47J8WIvkZLFGPQ6161"));
        public IWebElement OrganizationSummaryLinkGTCJ9YXdwOW2uDrZJoL84ZqGg6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCJ9YXdwOW2uDrZJoL84ZqGg6161"));
        public IWebElement OrganizationSummaryLinkGTCJEKHflaoib8QnrpzOP9qWQ6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCJEKHflaoib8QnrpzOP9qWQ6161"));
        public IWebElement OrganizationSummaryLinkGTCLLcuT471gV143mygHnPkKt0A6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCLLcuT471gV143mygHnPkKt0A6161"));
        public IWebElement OrganizationSummaryLinkGTCM7fr7wz43nRP7pxgAEXP4BQ6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCM7fr7wz43nRP7pxgAEXP4BQ6161"));
        public IWebElement OrganizationSummaryLinkGTCXxkTFvpyDa47UwrjBNBbYPw6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCXxkTFvpyDa47UwrjBNBbYPw6161"));
        public IWebElement OrganizationSummaryLinkGTCYJVZ74ieyWJIx434398WxOjg6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCYJVZ74ieyWJIx434398WxOjg6161"));
        public IWebElement OrganizationSummaryLinkGTCqC9lKip9hliHH43431qc2nPQ6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCqC9lKip9hliHH43431qc2nPQ6161"));
        public IWebElement OrganizationSummaryLinkGTCqr47WhlV1UmigenKGmCfcdQ6161 => Browser.FindElement(By.Id("OrganizationSummaryLinkGTCqr47WhlV1UmigenKGmCfcdQ6161"));
        public IWebElement OrganizationsButton => Browser.FindElement(By.Id("OrganizationsButton"));
        public IWebElement OrganizationsReportLink => Browser.FindElement(By.Id("OrganizationsReportLink"));
        public IWebElement QuickBackToTopLink => Browser.FindElement(By.Id("QuickBackToTopLink"));
        public IWebElement RescheduleLinkGTC43az2tfR9mR1al472h8AP6Ig6161 => Browser.FindElement(By.Id("RescheduleLinkGTC43az2tfR9mR1al472h8AP6Ig6161"));
        public IWebElement RescheduleLinkGTC47jpGaAfgHdno43wvWmvV43xQ6161 => Browser.FindElement(By.Id("RescheduleLinkGTC47jpGaAfgHdno43wvWmvV43xQ6161"));
        public IWebElement RescheduleLinkGTC6C1CRHkDt6b0KVXHCdPjbg6161 => Browser.FindElement(By.Id("RescheduleLinkGTC6C1CRHkDt6b0KVXHCdPjbg6161"));
        public IWebElement RescheduleLinkGTC7teUUHinAF2avtmvukp5Ag6161 => Browser.FindElement(By.Id("RescheduleLinkGTC7teUUHinAF2avtmvukp5Ag6161"));
        public IWebElement RescheduleLinkGTCAxTWsbQ3GJcXjtrxdbcpJA6161 => Browser.FindElement(By.Id("RescheduleLinkGTCAxTWsbQ3GJcXjtrxdbcpJA6161"));
        public IWebElement RescheduleLinkGTCCV3Yzj7qYqEK1zIGQGMgSg6161 => Browser.FindElement(By.Id("RescheduleLinkGTCCV3Yzj7qYqEK1zIGQGMgSg6161"));
        public IWebElement RescheduleLinkGTCEGhSjJkjS47J8WIvkZLFGPQ6161 => Browser.FindElement(By.Id("RescheduleLinkGTCEGhSjJkjS47J8WIvkZLFGPQ6161"));
        public IWebElement RescheduleLinkGTCJ9YXdwOW2uDrZJoL84ZqGg6161 => Browser.FindElement(By.Id("RescheduleLinkGTCJ9YXdwOW2uDrZJoL84ZqGg6161"));
        public IWebElement RescheduleLinkGTCJEKHflaoib8QnrpzOP9qWQ6161 => Browser.FindElement(By.Id("RescheduleLinkGTCJEKHflaoib8QnrpzOP9qWQ6161"));
        public IWebElement RescheduleLinkGTCLLcuT471gV143mygHnPkKt0A6161 => Browser.FindElement(By.Id("RescheduleLinkGTCLLcuT471gV143mygHnPkKt0A6161"));
        public IWebElement RescheduleLinkGTCM7fr7wz43nRP7pxgAEXP4BQ6161 => Browser.FindElement(By.Id("RescheduleLinkGTCM7fr7wz43nRP7pxgAEXP4BQ6161"));
        public IWebElement RescheduleLinkGTCXxkTFvpyDa47UwrjBNBbYPw6161 => Browser.FindElement(By.Id("RescheduleLinkGTCXxkTFvpyDa47UwrjBNBbYPw6161"));
        public IWebElement RescheduleLinkGTCYJVZ74ieyWJIx434398WxOjg6161 => Browser.FindElement(By.Id("RescheduleLinkGTCYJVZ74ieyWJIx434398WxOjg6161"));
        public IWebElement RescheduleLinkGTCqC9lKip9hliHH43431qc2nPQ6161 => Browser.FindElement(By.Id("RescheduleLinkGTCqC9lKip9hliHH43431qc2nPQ6161"));
        public IWebElement RescheduleLinkGTCqr47WhlV1UmigenKGmCfcdQ6161 => Browser.FindElement(By.Id("RescheduleLinkGTCqr47WhlV1UmigenKGmCfcdQ6161"));
        public IWebElement SearchButton => Browser.FindElement(By.Id("SearchButton"));
        public IWebElement SearchForm => Browser.FindElement(By.Id("SearchForm"));
        public IWebElement SecurityGroupsLink => Browser.FindElement(By.Id("SecurityGroupsLink"));
        public IWebElement SkipToMainContent508 => Browser.FindElement(By.Id("SkipToMainContent508"));
        public IWebElement ToDateField => Browser.FindElement(By.Id("ToDateField"));
        public IWebElement UsersLink => Browser.FindElement(By.Id("UsersLink"));
    }
}
